feat: #2 criando card de notícias
practice-uffs/app-practice-react-native pull request #12
Opened 2022-08-31 01:24 UTC by zorteaadriano

- Deixei o elemento clicável mas leva pra tela inicial.
- A imagem do banner tem que ser proporcional (mais largura do que altura), pra ficar uma boa visualização (utilizei como teste um banner padrão que tava na pasta já).

[Screencast from 30-08-2022 22:17:35.webm](https://user-images.githubusercontent.com/74692811/187571779-994deb64-d29a-4595-ad0f-c148cc280e88.webm)

2022-08-31 11:16 UTC, alissonpeloso commented
@zorteaadriano, quando eu tento navegar para a página de news ele dá um erro e fecha o expo, não entendi qual o problema.

Tá dando esse erro aqui: 
![image](https://user-images.githubusercontent.com/51202705/187666088-12d674a8-1b58-44f5-b652-f6d07e3b7b63.png)

Outra coisa, acho que teria que ser implementado a requisição das noticias do site do practice com aquele feed.xml e ver as informações necessárias para criar o card.

2022-08-31 11:16 UTC, alissonpeloso requested changes
.

2022-08-31 20:57 UTC, zorteaadriano commented
beleza @alissonpeloso, to tentando fazer algo parecido com esse tutorial.
https://www.youtube.com/watch?v=k8hz8WIxhAA&ab_channel=StackMobile

2022-09-02 14:17 UTC, alissonpeloso commented
@zorteaadriano, quando realizar as alterações e atualizar na branch me avisa, aí faço a revisão novamente

2022-09-06 03:28 UTC, zorteaadriano commented
@alisson, descobri os problemas que estavam ocorrendo para renderizar a tela: 

O erro de require cycle no botão da tela incial era um import de rotas na página do componente da notícias.

O problema da tela fechando sozinha no app era que o react estava tratando diferente as propriedades de estilização declarados no stylesheet, quando eu definia margin: '20px' ele exibia na versão web mas quebrava no app, o correto foi definir como margin:20 somente, sem o px, aí renderizou normal.

Se puder testar pra ver se ficou ok no seu celular, acredito que agora esteja funcional.

2022-09-06 11:10 UTC, alissonpeloso commented
> @Alisson, descobri os problemas que estavam ocorrendo para renderizar a tela:
> 
> O erro de require cycle no botão da tela incial era um import de rotas na página do componente da notícias.
> 
> O problema da tela fechando sozinha no app era que o react estava tratando diferente as propriedades de estilização declarados no stylesheet, quando eu definia margin: '20px' ele exibia na versão web mas quebrava no app, o correto foi definir como margin:20 somente, sem o px, aí renderizou normal.
> 
> Se puder testar pra ver se ficou ok no seu celular, acredito que agora esteja funcional.

Pior que tomei esse erro ontem e era esse mesmo negócio, tinha anotado pra ir olhar no teu código pra ver se não tinha algo assim kkk, vou olhar daqui a pouco

2022-09-06 11:41 UTC, alissonpeloso approved these changes
Só ajustar os conflitos dos commits anteriores

2022-09-06 13:39 UTC, alissonpeloso commented
@zorteaadriano, depois de resolver os conflitos, acredito que dê para criar uma issue pra quando você clicar na noticia ela abrir a notícia completa. Aí teria que ver se fica melhor usando no próprio aplicativo, abrindo uma página com o conteúdo, ou se fica melhor direcionar pro site.

2022-09-06 14:21 UTC, merged