feat: add picker para selecionar campus ao efetuar login
practice-uffs/app-practice-react-native pull request #23
Opened 2022-09-22 20:30 UTC by alissonpeloso

Nessa issue apenas foi adicionado um picker select para selecionar o campus ao logar no aplicativo, assim teremos essa informação vinculado ao objeto `user` que é salvo no storage e fica ativo no contexto do aplicativo.

fix: #9

2022-09-27 14:15 UTC, stefanimeneghetti requested changes
Ao testar no celular o campus de Cerro Largo parecia estar pré-selecionado mas não foi possível fazer o login com essa pré-seleção e para fazer o login com o campus de Cerro Largo precisei selecionar outro campus e depois selecionar Cerro Largo novamente. 

Creio que seria bom ou deixar um campus selecionado inicialmente e permitir o login sem alterações ou deixar algo como "selecione seu campus" como placeholder.

2022-09-27 16:42 UTC, alissonpeloso commented
> Ao testar no celular o campus de Cerro Largo parecia estar pré-selecionado mas não foi possível fazer o login com essa pré-seleção e para fazer o login com o campus de Cerro Largo precisei selecionar outro campus e depois selecionar Cerro Largo novamente.
> 
> Creio que seria bom ou deixar um campus selecionado inicialmente e permitir o login sem alterações ou deixar algo como "selecione seu campus" como placeholder.

Estranho, testei várias vezes aqui agora e funcionou. Você testou pelo expo go ou pela web?

2022-09-27 16:53 UTC, stefanimeneghetti commented
> > Ao testar no celular o campus de Cerro Largo parecia estar pré-selecionado mas não foi possível fazer o login com essa pré-seleção e para fazer o login com o campus de Cerro Largo precisei selecionar outro campus e depois selecionar Cerro Largo novamente.
> > Creio que seria bom ou deixar um campus selecionado inicialmente e permitir o login sem alterações ou deixar algo como "selecione seu campus" como placeholder.
> 
> Estranho, testei várias vezes aqui agora e funcionou. Você testou pelo expo go ou pela web?

Pelo expo go, não sei se fiz algo errado mas não consegui clicar no botão de login sem trocar o campus pelo menos uma vez

2022-09-27 22:26 UTC, stefanimeneghetti approved these changes

2022-09-28 02:45 UTC, SWE3T approved these changes

2022-09-29 19:17 UTC, zorteaadriano approved these changes

2022-09-29 19:19 UTC, merged